# -*- coding: utf-8 -*-
"""Atividade Python 29/02/24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrwKnZTRnDbffxQF1RyFRmEqbFynWxpG

1 - Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.
"""

a=float(input('Insira um número: '))
if a>0:
  print('O número é positivo.')
else:
  print('O número é negativo.')

"""2 - Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.

"""

x=str(input('Insira uma letra maiúscula: '))
if x == 'F':
  print('Você é do sexo feminino.')
elif x == 'M':
  print('Você é do sexo masculino.')
else:
  print('Sexo inválido.')

"""

```
# Isto está formatado como código
```

3 - Faça um Programa que verifique se uma letra digitada é vogal ou consoante.
"""

vogais=['a', 'e', 'i', 'o', 'u']
k=(input('Digite uma letra:'))

if k in vogais:
    print('A letra é uma vogal.')
else:
    print('A letra é uma consoante.')

"""4 - Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno apresentar:
 - A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
 - A mensagem "Reprovado", se a média for menor do que sete;
 - A mensagem "Aprovado com Distinção", se a média for igual a dez.
"""

a=float(input('Digite a primeira nota: '))
b=float(input('Digite a segunda nota: '))
c = (a+b)//2
if c == 10:
  print('Aprovado com distinção! :)')
elif c < 7:
  print('Reprovado :(')
else:
  print('Aprovado :)')

"""5 - Faça um Programa que leia três números e mostre o maior deles.

> Bloco com recuo



"""

#1º método:
a=float(input('Digite um número: '))
b=float(input('Digite um número: '))
c=float(input('Digite um número: '))

if a>b and a>c:
    print('O maior número é: ', a)
elif b>a and b>c:
    print('O maior número é: ', b)
else:
      print('O maior número é: ', c)

maiornum=0
for i in range(3):
    numero =int(input(f"Digite o {i+1}º número: "))
    if numero[i] > maiornum:
        maiornum=numeros[i]

Print('O maior número é:', maiornum)

"""6 - Faça um Programa que leia três números e mostre o maior e o menor deles.

> Bloco com recuo


"""

a=float(input('Digite um número: '))
b=float(input('Digite um número: '))
c=float(input('Digite um número: '))

if a>b and a>c:
    print('O maior número é: ', a)
elif b>a and b>c:
    print('O maior número é: ', b)
else:
    print('O maior número é: ', c)

if a<b and a<c:
    print('O menor número é: ', a)
elif b<a and b<c:
    print('O menor número é: ', b)
else:
    print('O menor número é: ', c)

"""7 - Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.

"""

a=float(input('Digite um valor: '))
b=float(input('Digite um valor: '))
c=float(input('Digite um valor: '))

if a<b and a<c:
    print('O produto mais barato é o que custa', a, 'reais.')
elif b<a and b<c:
    print('O produto mais barato é o que custa', b, 'reais.')
else:
    print('O produto mais barato é o que custa', c, 'reais.')

"""8 - Faça um Programa que leia três números e mostre-os em ordem decrescente.

"""

a = []

for i in range(3):
  a.append(int(input('Digite um número:')))

a.sort(reverse=True)
print(a)

"""9 - As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
 - salários até R$ 280,00 (incluindo) : aumento de 20%
 - salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
 - salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
 - salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:
 - o salário antes do reajuste;
 - o percentual de aumento aplicado;
 - o valor do aumento;
 - o novo salário, após o aumento.
"""

sal=float(input('Insira o valor do salário:'))
if sal<= 280:
    print(f'O novo salário é {(sal*0.2) + 280} reais. Antes, o salário era de {sal}. Portando, o aumento foi de 20%, equivalendo a {sal*0.2} reais a mais.')
elif sal > 280 and sal < 700:
    print(f'O novo salário é de {(sal*0.15) + sal} reais). Antes, o salário era de {sal}. Portanto, o aumento foi de 15%, equivalendo a {sal*0.15} reais a mais.')
elif sal > 700 and sal < 1500:
    print(f'O novo salário é de {(sal*0.1) + sal} reais. Antes, era de {sal}. Portanto, sofreu reajuste de 10%, equivalendo a {sal*0.1} reais a mais.')
else:
    print(f'O novo salário é de {(sal*0.05) + sal} reais. Ante, era de {sal}. Portanto, seu reajuste foi de 5%, equivalendo a {sal*0.05} reais a mais.')

"""10 -Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo. Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
Dicas:
- Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
- Triângulo Equilátero: três lados iguais;
- Triângulo Isósceles: quaisquer dois lados iguais;
- Triângulo Escaleno: três lados diferentes;



"""

a=float(input('Determine um dos lados do triângulo:'))
b=float(input('Determine um dos lados do triângulo:'))
c=float(input('Determine um dos lados do triângulo:'))

#Verificar se é um triângulo
if (a+b)>c or (a+c)>b or (b+c)>a:
    if (a==b) and (a==c) and (b==c):
        print('É um triânculo equilátero.')
    elif (a==b) or (a==c) or (b==c):
        print('É um triângulo isóceles.')
    else:
        print('É um triângulo escaleno.')
else:
    print('Não é um triângulo.')
